#!/bin/bash
if [ $# != 3 ]; then
	echo "Usar: ./calc [Número] [Operador] [Número]"
exit 1
fi

case "$2" in
	x)
		echo "$1 * $3" | bc -l
		;;
	/)
		echo "$1 / $3" | bc -l
		;;
	+)
		echo "$1 + $3" | bc -l
		;;
	-)
		echo "$1 - $3" | bc -l
		;;
	*)
		echo "$2: operação inválida"
		;;
esac
