#!/bin/bash

while read -r linha; do
	if [[ -z "$linha" ]]; then
		break
	fi

	processada=$(echo "$linha" | sed 's/[^A-Za-z]//g' | tr '[:upper:]' '[:lower:]')

	invertida=$(echo "$processada" | rev)

	if [[ "$processada" == "$invertida" ]]; then
		echo "Yes"
	else
		echo "No"
	fi
done
